cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    admin:
      email: admin@gmail.com
      failed_login_attempts: 0
      first_name: Admin
      last_name: Baru
      logged_in: false
      password: $2b$12$OuGJENoQa1IbGLu9Ok5j1.TZxH6Ud1zEqTWIy1WGczJCnmeRvJm4W
